config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :attendances
  resources :events
  resources :users
  get "/", to: "events#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event
    after_create :welcome_send

    def welcome_send
        UserMailer.welcome_email(self.user).deliver_now
    end
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attendances
    #has_many :users, through: :attendances
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :attendances
    # has_many :events, through: :attendances
    has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: %i[ show edit update destroy ]

  # GET /attendances or /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1 or /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances or /attendances.json
  def create
    puts "#### OMG CREATING ATTENDANCE ####"
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: "Attendance was successfully created." }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1 or /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: "Attendance was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1 or /attendances/1.json
  def destroy
    @attendance.destroy!

    respond_to do |format|
      format.html { redirect_to attendances_path, notice: "Attendance was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def attendance_params
      params.expect(attendance: [ :stripe_customer_id, :user_id, :event_id ])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_path, notice: "Event was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.expect(event: [ :start_date, :duration, :title, :description, :price, :location ])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, notice: "User was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: [ :email, :encrypted_password, :description, :first_name, :last_name ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/_attendance.html.erb
<div id="<%= dom_id attendance %>">
  <p>
    <strong>Stripe customer:</strong>
    <%= attendance.stripe_customer_id %>
  </p>

</div>

app/views/attendances/_form.html.erb
<%= form_with(model: attendance) do |form| %>
  <% if attendance.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
        <% attendance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :stripe_customer_id, style: "display: block" %>
    <%= form.text_field :stripe_customer_id %>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
    <%= form.label :event_id, style: "display: block" %>
    <%= form.text_field :event_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<% content_for :title, "Editing attendance" %>

<h1>Editing attendance</h1>

<%= render "form", attendance: @attendance %>

<br>

<div>
  <%= link_to "Show this attendance", @attendance %> |
  <%= link_to "Back to attendances", attendances_path %>
</div>

app/views/attendances/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Attendances" %>

<h1>Attendances</h1>

<div id="attendances">
  <% @attendances.each do |attendance| %>
    <%= render attendance %>
    <p>
      <%= link_to "Show this attendance", attendance %>
    </p>
  <% end %>
</div>

<%= link_to "New attendance", new_attendance_path %>

app/views/attendances/new.html.erb
<% content_for :title, "New attendance" %>

<h1>New attendance</h1>

<%= render "form", attendance: @attendance %>

<br>

<%for n in User.all do%>
  <p>ID : <%= n.id%> | Name : <%= n.first_name%></p>
<%end%>

<%for n in Event.all do%>
  <p>ID : <%= n.id%> | Event : <%= n.title%></p>
<%end%>

<div>
  <%= link_to "Back to attendances", attendances_path %>
</div>

app/views/attendances/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @attendance %>

<div>
  <%= link_to "Edit this attendance", edit_attendance_path(@attendance) %> |
  <%= link_to "Back to attendances", attendances_path %>

  <%= button_to "Destroy this attendance", @attendance, method: :delete %>
</div>

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">

  <div class="card-simple">
    <h4>
      <%= event.title %>
    </h4>
    <p>
      <strong>Description:</strong>
      <%= event.description %>
    </p>
    <p>
      <strong>Date :</strong>
      <%= event.start_date %>
    </p>
    <p>
      <strong>Duration :</strong>
      <%= event.duration %> minutes
    </p>
    <p>
      <strong>Location:</strong>
      <%= event.location %>
    </p>
    <p>
      <%= event.price %> €
    </p>
  </div>
  

  





</div>

app/views/events/_event_list.html.erb
<% @events.each do |event| %>
    <section>
    <div class="section-content">
        <%= render event %>
        <p>
        <%= link_to "Show this event", event %>
        </p>
    </div>
    </section>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-label-input">
    <%= form.label :start_date, style: "display: block" %>
    <%= form.datetime_field :start_date %>
  </div>

  <div class="form-label-input">
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div class="form-label-input">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div class="form-label-text">
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div class="form-label-input">
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div class="form-label-input">
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div class="form-label-input">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<% content_for :title, "Editing event" %>

<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Events" %>

<div class="content">
  <section class="large-section">
    <div class="section-content">
      <h1>Events</h1>
      <p class="lead">Here are some nice event created by our members to try and go touch grass with a goal.</p>
      <p>So just be nice and go to some events. It will be fun and you'll for sure find new types of grass to touch anyway.</p>
      <p>Yes this is some stupid text to fill a bit more space so it's not that cringe</p>
    </div>
  </section>

  <%= render "event_list" %>

</div>

app/views/events/new.html.erb
<% content_for :title, "New event" %>



<div class="content">

  <section class="large-section">
    <div class="section-content">
      <h1>New event</h1>
      <p>Come on, go ahead and create a new event to bring life to this website. It really deserves it, I swear.</p>
    </div>
  </section>

  <section>
    <div class="section-content">
      <%= render "form", event: @event %>
    </div>
  </section>

  <section class="large-section">
    <div class="section-content">
      <%= link_to "Back to events", events_path %>
    </div>
  </section>

</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="content">

  <section class="large-section">
    <div class="section-content">
      <h1><%= @event.title %></h1>
    </div>
  </section>
  <section>
    <div class="section-content">
      <%= render @event %><br>
      <%if current_user && current_user.id == @event.user_id %>
        <%= link_to "Edit this event", edit_event_path(@event) %> |
        <%= link_to "Back to events", events_path %>
        <%= button_to "Destroy this event", @event, method: :delete %>
      <%end%>
    </div>
  </section>
</div>

app/views/layouts/_footer.html.erb
<footer>
    <div>
        <p>This project is a test</p>
        <p>This is a footer</p>
    </div>
    <div>
        <p>Contact me now <a href="https://www.google.com">here</a></p>
    </div>
    <div>
        <p>Tayles project</p>
        <p>2025_2026</p>
    </div>
</footer>

app/views/layouts/_nav.html.erb
<nav>
    <h1><a href="/">GoOut</a></h1>
    <ul class="nav-menu">
    <li><a href="<%= events_path %>">Home</a></li>
    <li><a href="<%= new_event_path %>">Make an event</a></li>
    <%if user_signed_in? %>
        <li><%= link_to "Mon Profil", user_path(current_user.id)%></li>
        <li><%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete} %></li>
        <%else%>
        <li><a href="<%= new_user_registration_path %>">S'inscrire</a></li>
        <li><a href="<%= new_user_session_path %>">Se connecter</a></li>
        <%end%>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous"> %>
    <%# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script> %>
    <title><%= content_for(:title) || "Go Out" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>



    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "/layouts/nav" %>

    <%= yield %>

    <%= render "/layouts/footer" %>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :encrypted_password, style: "display: block" %>
    <%= form.text_field :encrypted_password %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Encrypted password:</strong>
    <%= user.encrypted_password %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= user.description %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<p>testtt</p>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<div class="content">
  <section class="large-section">
    <div class="session-content">
      <h1>New user</h1>
    </div>
  </section>
  
  <%= render "form", user: @user %>
  <br>
  <div>
    <%= link_to "Back to users", users_path %>
  </div>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>